#ifndef _MCP41xxx_H
#define _MCP41xxx_H

#define	MCP41XXX_PORT		GPIOB
#define	MCP41XXX_CS_PIN 	GPIO_Pin_6
#define	MCP41XXX_SCK_PIN 	GPIO_Pin_3
#define	MCP41XXX_SI_PIN 	GPIO_Pin_4

#define MCP41XXX_CS_H		MCP41XXX_PORT->BSRR = MCP41XXX_CS_PIN	//BSRR是置位，BRR是复位
#define MCP41XXX_CS_L		MCP41XXX_PORT->BRR = MCP41XXX_CS_PIN

#define MCP41XXX_SCK_H		MCP41XXX_PORT->BSRR = MCP41XXX_SCK_PIN
#define MCP41XXX_SCK_L		MCP41XXX_PORT->BRR = MCP41XXX_SCK_PIN

#define MCP41XXX_SI_H		MCP41XXX_PORT->BSRR = MCP41XXX_SI_PIN
#define MCP41XXX_SI_L		MCP41XXX_PORT->BRR = MCP41XXX_SI_PIN



void GPIO_MCP41xxx_Config(void);
void MCP41xxx_Write_RES(u8 dat1);
#endif
